#!/usr/bin/env bash
# Configure nginx to listen on port 80 on all IPv4 addresses
sed -i 's/listen 127.0.0.1:80;/listen 0.0.0.0:80;/' /etc/nginx/sites-available/default
service nginx restart || /etc/init.d/nginx restart
