#!/usr/bin/env bash
# Install and configure nginx to serve a page with Holberton School

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart

nginx -v
curl -s localhost
