#!/usr/bin/env bash
# Install and configure nginx web server

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart

nginx -v 2>&1
curl -sI localhost | awk 'NR==1 {print $2}'
curl -s localhost
