#!/usr/bin/env bash
# Install nginx and configure a 301 redirect for /redirect_me

apt-get update -y
apt-get install -y nginx

REDIRECT='rewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'

grep -q "redirect_me" /etc/nginx/sites-available/default || \
sed -i "/listen 80 default_server;/a $REDIRECT" /etc/nginx/sites-available/default

service nginx start
service nginx restart
