#!/usr/bin/env bash
# Install and configure nginx to redirect /redirect_me with a 301 status

apt-get update -y
apt-get install -y nginx

sed -i '/listen 80 default_server;/a \
\n\trewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default

service nginx start
service nginx restart
